### ISSUE TITLE
Issue when trying to call from CommonJS module

### ISSUE THREAD

**Issue by robross0606** [ghinks/ls-remote-versions#105]
When invoking via CJM like this:
```js
const ls = require('ls-remote-versions').default
ls ('@nurocor/node-graphql-utils', '^2.0.1', 'https://artifact.nurocorinternal.com/repository/npm-internal/')
```
I get an error:
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at parseVersions (C:\Code\gitops\ncp-dependency-graph\node_modules\ls-remote-versions\lib\parseVersions\index.js:9:17)
    at _callee$ (C:\Code\gitops\ncp-dependency-graph\node_modules\ls-remote-versions\lib\index.js:50:51)
    at tryCatch (C:\Code\gitops\ncp-dependency-graph\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Code\gitops\ncp-dependency-graph\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (C:\Code\gitops\ncp-dependency-graph\node_modules\regenerator-runtime\runtime.js:118:21)
    at asyncGeneratorStep (C:\Code\gitops\ncp-dependency-graph\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Code\gitops\ncp-dependency-graph\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
The problem appears to be that `this` is `undefined` at:
```js
  return function getPackageVersions(_x4, _x5, _x6) {
    return _ref2.apply(this, arguments);
  };
```

**Comment by ghinks** [comment]
I'm so sorry for missing this issue. I'll be looking at it shortly :)

**Comment by ghinks** [comment]
I have updated the documentation for the module scenario for esm as 

```javascript
import ls from "ls-remote-versions/src/index.js";

ls('debug', '2').then(result => console.log(result));
```

I shall look into the Common JS scenario next.
